export type QuranWord={id:string;verseKey:string;position:number;text:string;audio?:string};
export type QuranAyah={verseKey:string;surah:number;ayah:number;text:string;words:QuranWord[];audio?:string};
const AYAH:QuranAyah={
 verseKey:"78:11",surah:78,ayah:11,text:"وَجَعَلْنَا ٱلنَّهَارَ مَعَاشًا",
 words:[
  {id:"78:11:1",verseKey:"78:11",position:1,text:"وَجَعَلْنَا"},
  {id:"78:11:2",verseKey:"78:11",position:2,text:"ٱلنَّهَارَ"},
  {id:"78:11:3",verseKey:"78:11",position:3,text:"مَعَاشًا"}
 ],
 audio:"https://everyayah.com/data/Alafasy_128kbps/078011.mp3"
};
export const QuranService={
 getAyah:async(verseKey:string)=>verseKey===AYAH.verseKey?AYAH:null,
 getWords:async(verseKey:string)=>(await QuranService.getAyah(verseKey))?.words??[],
 getAyahAudio:async(verseKey:string)=>(await QuranService.getAyah(verseKey))?.audio??null
};
/*
 Production rule: replace bundled seed content with a verified full IndoPak 15-line dataset.
 Canonical Quran text must never be generated by an LLM.
*/